/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as WorkspacesWorkspaceIdTasksRouteImport } from './routes/workspaces.$workspaceId.tasks'
import { Route as WorkspacesWorkspaceIdTasksTaskIdRouteImport } from './routes/workspaces.$workspaceId.tasks.$taskId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdTasksRoute =
  WorkspacesWorkspaceIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdTasksTaskIdRoute =
  WorkspacesWorkspaceIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => WorkspacesWorkspaceIdTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/sessions': typeof SessionsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/tasks': typeof WorkspacesWorkspaceIdTasksRouteWithChildren
  '/workspaces/$workspaceId/tasks/$taskId': typeof WorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/sessions': typeof SessionsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/tasks': typeof WorkspacesWorkspaceIdTasksRouteWithChildren
  '/workspaces/$workspaceId/tasks/$taskId': typeof WorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/sessions': typeof SessionsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/workspaces/$workspaceId/tasks': typeof WorkspacesWorkspaceIdTasksRouteWithChildren
  '/workspaces/$workspaceId/tasks/$taskId': typeof WorkspacesWorkspaceIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rules'
    | '/sessions'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/tasks'
    | '/workspaces/$workspaceId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/sessions'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/tasks'
    | '/workspaces/$workspaceId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/rules'
    | '/sessions'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/tasks'
    | '/workspaces/$workspaceId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesRoute: typeof RulesRoute
  SessionsRoute: typeof SessionsRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/tasks': {
      id: '/workspaces/$workspaceId/tasks'
      path: '/tasks'
      fullPath: '/workspaces/$workspaceId/tasks'
      preLoaderRoute: typeof WorkspacesWorkspaceIdTasksRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/tasks/$taskId': {
      id: '/workspaces/$workspaceId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/workspaces/$workspaceId/tasks/$taskId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdTasksTaskIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdTasksRoute
    }
  }
}

interface WorkspacesWorkspaceIdTasksRouteChildren {
  WorkspacesWorkspaceIdTasksTaskIdRoute: typeof WorkspacesWorkspaceIdTasksTaskIdRoute
}

const WorkspacesWorkspaceIdTasksRouteChildren: WorkspacesWorkspaceIdTasksRouteChildren =
  {
    WorkspacesWorkspaceIdTasksTaskIdRoute:
      WorkspacesWorkspaceIdTasksTaskIdRoute,
  }

const WorkspacesWorkspaceIdTasksRouteWithChildren =
  WorkspacesWorkspaceIdTasksRoute._addFileChildren(
    WorkspacesWorkspaceIdTasksRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdTasksRoute: typeof WorkspacesWorkspaceIdTasksRouteWithChildren
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdTasksRoute: WorkspacesWorkspaceIdTasksRouteWithChildren,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRoute: RulesRoute,
  SessionsRoute: SessionsRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
